name: CD – social media Deployment
on:
  workflow_dispatch:
jobs:
  run--deploy:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: website_pipeline
      environment: prod
      tools: '["deploy"]'
