# .github/workflows/ad-analytics.yml
name: Ad Analytics

on:
  push:
    branches:
      - main
    paths:
      - 'ad_analytics_pipeline/**'

jobs:
  run-ad-analytics:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: ad_analytics_pipeline
      environment: dev
      tools: '["bash"]'
    # forward all repo secrets (including GCP_SA_KEY)
    secrets: inherit
