# .github/workflows/cd-ad-analytics.yml
name: CD – Ad Analytics

on:
  push:
    branches:
      - main
    paths:
      - 'ad_analytics_pipeline/**'

jobs:
  run-ad-analytics:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: ad_analytics_pipeline
      environment: prod
      tools: '["bash"]'
    secrets:
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_REGION:  ${{ secrets.GCP_REGION }}
      GCP_SA_KEY:  ${{ secrets.GCP_SA_KEY }}
