name: CD – AI Pipeline Deployment

on:
  workflow_dispatch:

jobs:
  deploy-ai-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: ai_pipeline
      environment: prod
      tools: '["deploy"]'
