name: CD – AI Model Deployment

on:
  workflow_dispatch:

jobs:
  deploy-ai-model:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & push Docker image
        run: |
          IMAGE_NAME="ai-model:${{ github.sha }}"
          docker build -t "$IMAGE_NAME" ai_pipeline
          docker push "$IMAGE_NAME"
      - name: Deploy to Kubernetes
        run: |
          # your kubectl apply / helm upgrade here
