name: CD – ad analytics Deployment

on:
  workflow_dispatch:

jobs:
  deploy-ad_analytics-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: ad_analytics_pipeline
      environment: prod
      tools: '["deploy"]'
