# .github/workflows/ad-analytics.yml
name: Ad Analytics

on:
  push:
    paths:
      - 'ad_analytics_pipeline/**'

jobs:
  run-ad-analytics:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: ad_analytics_pipeline
      environment: dev
      tools: '["bash"]'
    secrets:
      # map your repo‐level secrets into the reusable workflow
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_REGION:  ${{ secrets.GCP_REGION }}
      GCP_SA_KEY:  ${{ secrets.GCP_SA_KEY }}
