name: CD – chatbot Deployment

on:
  workflow_dispatch:

jobs:
  deploy-chatbot-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: chatbot_pipeline
      environment: prod
      tools: '["deploy"]'
