name: CD – content personalization Deployment

on:
  workflow_dispatch:

jobs:
  deploy-content_personalization-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: content_personalization_pipeline
      environment: prod
      tools: '["deploy"]'
