name: CD – email campaign Deployment

on:
  workflow_dispatch:

jobs:
  deploy-email_campaign-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: email_campaign_pipeline
      environment: prod
      tools: '["deploy"]'
