name: CD – iac Deployment
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: iac_pipeline
      environment: prod
      tools: '["deploy"]'
