name: CD – mlops Deployment
on:
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: mlops_pipeline
      environment: prod
      tools: '["deploy"]'
