name: CD – robotics Deployment

on:
  workflow_dispatch:

jobs:
  deploy-robotics-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: robotics_pipeline
      environment: prod
      tools: '["deploy"]'
