name: CI – UcontentUcreation Pipeline

on:
  push:
    paths:
      - 'content_creation_pipeline/**'
  workflow_dispatch:

jobs:
  run-content-creation-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: content_creation_pipeline
      environment: dev
      tools: '["build","test","deploy"]'
