name: CI – email campaign Pipeline

on:
  push:
    paths:
      - 'email_campaign_pipeline/**'
  workflow_dispatch:

jobs:
  run-email_campaign-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: email_campaign_pipeline
      environment: dev
      tools: '["stub1","stub2","stub3"]'
