name: CI – Email Campaign Pipeline

on:
  push:
    paths:
      - 'email_campaign_pipeline/**'
  workflow_dispatch:

jobs:
  run-email-campaign-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: email_campaign_pipeline
      environment: dev
      tools: '["lint","test_send","deploy"]'
