name: CI – ingestion Pipeline

on:
  push:
    paths:
      - 'ingestion_pipeline/**'
  workflow_dispatch:

jobs:
  run-ingestion-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: ingestion_pipeline
      environment: dev
      tools: '["build","test","deploy"]'
