name: CI – UlandingUpage Pipeline

on:
  push:
    paths:
      - 'landing_page_pipeline/**'
  workflow_dispatch:

jobs:
  run-landing_page-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: landing_page_pipeline
      environment: dev
      tools: '["stub1","stub2","stub3"]'
