name: CI – Lead Generation Pipeline

on:
  push:
    paths:
      - 'lead_generation_pipeline/**'
  workflow_dispatch:

jobs:
  run-lead-generation-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: lead_generation_pipeline
      environment: dev
      tools: '["ingest","enrich","score","dispatch"]'
