name: CI – UleadUgeneration Pipeline

on:
  push:
    paths:
      - 'lead_generation_pipeline/**'
  workflow_dispatch:

jobs:
  run-lead_generation-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: lead_generation_pipeline
      environment: dev
      tools: '["stub1","stub2","stub3"]'
