name: CI – marketing campaign Pipeline

on:
  push:
    paths:
      - 'marketing_campaign_pipeline/**'
  workflow_dispatch:

jobs:
  run-marketing_campaign-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: marketing_campaign_pipeline
      environment: dev
      tools: '["stub1","stub2","stub3"]'
