name: CI – Social Media Pipeline

on:
  push:
    paths:
      - 'social_media_pipeline/**'
  workflow_dispatch:

jobs:
  run-social-media-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: social_media_pipeline
      environment: dev
      tools: '["schedule","fetch_metrics","report"]'
