name: CI – UsocialUmedia Pipeline

on:
  push:
    paths:
      - 'social_media_pipeline/**'
  workflow_dispatch:

jobs:
  run-social_media-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: social_media_pipeline
      environment: dev
      tools: '["stub1","stub2","stub3"]'
