# .github/workflows/ci-template.yml

permissions:
  contents: read    # allow actions/checkout to fetch the repo

on:
  workflow_call:
    inputs:
      pipeline-dir:
        description: "Path to the pipeline directory"
        required: true
        type: string
      environment:
        description: "Environment (dev/staging/prod)"
        required: true
        type: string
      tools:
        description: "JSON array of tools"
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Report inputs
        run: |
          echo "Pipeline-dir = ${{ inputs.pipeline-dir }}"
          echo "Environment = ${{ inputs.environment }}"
          echo "Tools       = ${{ inputs.tools }}"
