# .github/workflows/ci-template.yml
on:
  workflow_call:
    inputs:
      pipeline-dir:
        description: 'Path to the pipeline directory'
        required: true
        type: string
      environment:
        description: 'Environment (dev/staging/prod)'
        required: true
        type: string
      tools:
        description: 'JSON array of tools (e.g. ["npm","docker","helm"])'
        required: true
        type: string

jobs:
  prepare:
    name: Prepare Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load helper scripts
        run: |
          source _Conventions/helpers.sh
          init_pipeline "${{ inputs.pipeline-dir }}" "${{ inputs.environment }}"

  build:
    name: Build & Deploy Steps
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: ${{ fromJson(inputs.tools) }}
    steps:
      - name: Run tool step ${{ matrix.tool }}
        uses: actions/checkout@v3
        run: |
          cp -R _Conventions "${{ inputs.pipeline-dir }}"
          source "${{ inputs.pipeline-dir }}/_Conventions/helpers.sh"
          run_tool_step "${{ matrix.tool }}" "${{ inputs.pipeline-dir }}"

  notify:
    name: Notify Status
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send notification
        uses: actions/checkout@v3
        run: |
          cp -R _Conventions "${{ inputs.pipeline-dir }}"
          source "${{ inputs.pipeline-dir }}/_Conventions/helpers.sh"
          notify_status "${{ job.status }}" "${{ inputs.pipeline-dir }}"
