# .github/workflows/ci-template.yml
on:
  workflow_call:
    inputs:
      pipeline-dir:
        description: 'Path to the pipeline directory'
        required: true
      environment:
        description: 'Environment name (dev/staging/prod)'
        required: true
      tools:
        description: 'JSON array of tools to run (e.g. ["npm","docker"])'
        required: true

jobs:
  prepare:
    name: Prepare Workspace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load helper scripts
        run: |
          source _Conventions/helpers.sh
          init_pipeline "\${{ inputs.pipeline-dir }}" "\${{ inputs.environment }}"

  build:
    name: Build & Deploy Steps
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: \${{ fromJson(inputs.tools) }}
    steps:
      - name: Execute tool step \${{ matrix.tool }}
        run: run_tool_step "\${{ matrix.tool }}" "\${{ inputs.pipeline-dir }}"

  notify:
    name: Notify Status
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Send notification
        run: notify_status "\${{ job.status }}" "\${{ inputs.pipeline-dir }}"
EOF
