# .github/workflows/ci-template.yml
on:
  workflow_call:
    # 👉 tell GH which secrets this workflow expects
    secrets:
      GCP_PROJECT:
        description: 'Your GCP project ID'
        required: true
      GCP_REGION:
        description: 'Your GCP region'
        required: true
      GCP_SA_KEY:
        description: 'Base64-encoded GCP service-account JSON key'
        required: true

    inputs:
      pipeline-dir:
        description: 'Path to the pipeline directory'
        required: true
        type: string
      environment:
        description: 'Environment (dev/staging/prod)'
        required: true
        type: string
      tools:
        description: 'JSON array of tools (e.g. ["npm","docker"])'
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      # now these will actually be populated
      GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      GCP_REGION:  ${{ secrets.GCP_REGION }}
      GCP_SA_KEY:  ${{ secrets.GCP_SA_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          fetch-depth: 1
          persist-credentials: false

      - name: Decode & activate GCP service account
        run: |
          echo "Decoding GCP_SA_KEY…"
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/sa.json
          if [[ ! -s /tmp/sa.json ]]; then
            echo "/tmp/sa.json is empty or missing—check your GCP_SA_KEY secret!"
            exit 1
          fi
          gcloud auth activate-service-account --key-file=/tmp/sa.json
          gcloud config set project $GCP_PROJECT

      - name: Report inputs
        run: |
          echo "Pipeline-dir = ${{ inputs.pipeline-dir }}"
          echo "Environment = ${{ inputs.environment }}"
          echo "Tools       = ${{ inputs.tools }}"

      - name: Extract raw data
        run: bash ${{ inputs.pipeline-dir }}/extract.sh

      - name: Transform data
        run: bash ${{ inputs.pipeline-dir }}/transform.sh

      - name: Load into target
        run: bash ${{ inputs.pipeline-dir }}/load.sh
