name: CI – Website Pipeline

on:
  push:
    paths:
      - 'website_pipeline/**'
  workflow_dispatch:

jobs:
  run-website-pipeline:
    uses: ./.github/workflows/ci-template.yml
    with:
      pipeline-dir: ingestion_pipeline/financial
      environment: dev
      tools: '["npm","docker","helm"]'
