name: CI – Website Pipeline

on:
  push:
    paths:
      - 'website_pipeline/**'
  workflow_dispatch:

jobs:
  run-website-pipeline:
    uses: ./.github/workflows/ci-template.yml@v1.0.0
    with:
      pipeline-dir: website_pipeline
      environment: dev
      tools: '["npm","docker","helm"]'
